# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

setuplambdaMVR_colwise <- function(Y, Z, nlam, setlam) {
    .Call(`_pqr_setuplambdaMVR_colwise`, Y, Z, nlam, setlam)
}

setuplambdaMVR_lasso <- function(Y, Z1, nlam, setlam) {
    .Call(`_pqr_setuplambdaMVR_lasso`, Y, Z1, nlam, setlam)
}

EstMVR_colwise <- function(Y, Z, W, lambda, optsList, optsList_pen) {
    .Call(`_pqr_EstMVR_colwise`, Y, Z, W, lambda, optsList, optsList_pen)
}

EstMVR_lasso <- function(Y, Z1, W, lambda, optsList, optsList_pen) {
    .Call(`_pqr_EstMVR_lasso`, Y, Z1, W, lambda, optsList, optsList_pen)
}

